name: AuthConnector
main: truelauncherauthconnector.Main
version: 4.0
author: _Shevchik_
load: STARTUP
depend: [ProtocolLib]
commands:
  authconnector:
    usage: authconnector reload - reload config
